name: Simple Workflow

on:
    workflow_dispatch:
      inputs:
        var1:
          description: 'Data to logging'
          required: true
          default: 'default'
jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 ADD INFO FROM UI
          run: |
            sudo chmod 777 /home/runner/work/devops-school/devops-school/output.txt
            echo "\nUI var: ${{ github.event.inputs.var1 }}" >> /home/runner/work/devops-school/devops-school/output.txt
        - name: 1.3 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: output.txt
              path: /home/runner/work/devops-school/devops-school/output.txt
